/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.memory_game.app.project;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int back_cover=0x7f020000;
        public static final int i0=0x7f020001;
        public static final int i1=0x7f020002;
        public static final int i10=0x7f020003;
        public static final int i11=0x7f020004;
        public static final int i12=0x7f020005;
        public static final int i13=0x7f020006;
        public static final int i14=0x7f020007;
        public static final int i15=0x7f020008;
        public static final int i16=0x7f020009;
        public static final int i17=0x7f02000a;
        public static final int i18=0x7f02000b;
        public static final int i19=0x7f02000c;
        public static final int i2=0x7f02000d;
        public static final int i20=0x7f02000e;
        public static final int i21=0x7f02000f;
        public static final int i22=0x7f020010;
        public static final int i23=0x7f020011;
        public static final int i3=0x7f020012;
        public static final int i4=0x7f020013;
        public static final int i5=0x7f020014;
        public static final int i6=0x7f020015;
        public static final int i7=0x7f020016;
        public static final int i8=0x7f020017;
        public static final int i9=0x7f020018;
    }
    public static final class id {
        public static final int addIngredientsButton=0x7f050028;
        public static final int card01=0x7f050000;
        public static final int card02=0x7f050001;
        public static final int card03=0x7f050002;
        public static final int card04=0x7f050003;
        public static final int card05=0x7f050004;
        public static final int card06=0x7f050005;
        public static final int card07=0x7f050006;
        public static final int card08=0x7f050007;
        public static final int card09=0x7f050008;
        public static final int card10=0x7f050009;
        public static final int card11=0x7f05000a;
        public static final int card12=0x7f05000b;
        public static final int card13=0x7f05000c;
        public static final int card14=0x7f05000d;
        public static final int card15=0x7f05000e;
        public static final int card16=0x7f05000f;
        public static final int card17=0x7f050010;
        public static final int card18=0x7f050011;
        public static final int card19=0x7f050012;
        public static final int card20=0x7f050013;
        public static final int card21=0x7f050014;
        public static final int card22=0x7f050015;
        public static final int card23=0x7f050016;
        public static final int card24=0x7f050017;
        public static final int card25=0x7f050018;
        public static final int card26=0x7f050019;
        public static final int card27=0x7f05001a;
        public static final int card28=0x7f05001b;
        public static final int cocktailsAddButton=0x7f050024;
        public static final int cocktailsAddIngredientsButton=0x7f050025;
        public static final int cocktailsTextView=0x7f05001e;
        public static final int coctailsIngredientsLayout=0x7f05001f;
        public static final int coctailsNameEditText=0x7f050020;
        public static final int garnishSpinner=0x7f050023;
        public static final int glassSpinner=0x7f050022;
        public static final int indredientsEditText=0x7f050027;
        public static final int ingredientsTextView=0x7f050026;
        public static final int ma_text1=0x7f05001c;
        public static final int ma_text2=0x7f05001d;
        public static final int methodSpinner=0x7f050021;
        public static final int playAddIngredientsButton=0x7f050030;
        public static final int playAnswer=0x7f05002f;
        public static final int playCocktailName=0x7f05002b;
        public static final int playGarnishSpinner=0x7f05002e;
        public static final int playGlassSpinner=0x7f05002d;
        public static final int playIngredientsLayout=0x7f050029;
        public static final int playMethodSpinner=0x7f05002c;
        public static final int playScore=0x7f05002a;
    }
    public static final class layout {
        public static final int activity_main=0x7f030000;
        public static final int cocktails=0x7f030001;
        public static final int ingredients=0x7f030002;
        public static final int play=0x7f030003;
        public static int activity_find_player;
        public static int activity_highscores;
        public static int activity_selection_screen;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int cocktailsButton=0x7f040005;
        public static final int hello_msg=0x7f040001;
        public static final int ingredientsButton=0x7f040004;
        public static final int menu_settings=0x7f040002;
        public static final int placeHolderButton=0x7f040006;
        public static final int title_activity_main=0x7f040003;
    }
}
